package com.sheng.android.policetalk.modal;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "CONVERSATION".
 */
@Entity
public class Conversation {

    @Id
    private Long id;
    private int user_id;

    @NotNull
    private String type;
    private int target_id;
    private long unread_count;

    @Generated
    public Conversation() {
    }

    public Conversation(Long id) {
        this.id = id;
    }

    @Generated
    public Conversation(Long id, int user_id, String type, int target_id) {
        this.id = id;
        this.user_id = user_id;
        this.type = type;
        this.target_id = target_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getUser_id() {
        return user_id;
    }

    public void setUser_id(int user_id) {
        this.user_id = user_id;
    }

    @NotNull
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(@NotNull String type) {
        this.type = type;
    }

    public int getTarget_id() {
        return target_id;
    }

    public void setTarget_id(int target_id) {
        this.target_id = target_id;
    }

    public long getUnread_count() {
        return unread_count;
    }

    public void setUnread_count(long unread_count) {
        this.unread_count = unread_count;
    }
}
