package com.sheng.android.policetalk.modal;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sheng.android.policetalk.modal.Voice_Message;
import com.sheng.android.policetalk.modal.Conversation;

import com.sheng.android.policetalk.modal.Voice_MessageDao;
import com.sheng.android.policetalk.modal.ConversationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig voice_MessageDaoConfig;
    private final DaoConfig conversationDaoConfig;

    private final Voice_MessageDao voice_MessageDao;
    private final ConversationDao conversationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        voice_MessageDaoConfig = daoConfigMap.get(Voice_MessageDao.class).clone();
        voice_MessageDaoConfig.initIdentityScope(type);

        conversationDaoConfig = daoConfigMap.get(ConversationDao.class).clone();
        conversationDaoConfig.initIdentityScope(type);

        voice_MessageDao = new Voice_MessageDao(voice_MessageDaoConfig, this);
        conversationDao = new ConversationDao(conversationDaoConfig, this);

        registerDao(Voice_Message.class, voice_MessageDao);
        registerDao(Conversation.class, conversationDao);
    }
    
    public void clear() {
        voice_MessageDaoConfig.clearIdentityScope();
        conversationDaoConfig.clearIdentityScope();
    }

    public Voice_MessageDao getVoice_MessageDao() {
        return voice_MessageDao;
    }

    public ConversationDao getConversationDao() {
        return conversationDao;
    }

}
