package com.sheng.android.policetalk.modal;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "VOICE__MESSAGE".
 */
@Entity
public class Voice_Message {

    @Id
    private Long id;
    private int owner;
    private int type;
    private int target_id;
    private int user_id;
    private int voice_length;

    @NotNull
    private String voice_path;
    private boolean read;

    @NotNull
    private java.util.Date date_time;

    @Generated
    public Voice_Message() {
    }

    public Voice_Message(Long id) {
        this.id = id;
    }

    @Generated
    public Voice_Message(Long id, int owner, int type, int target_id, int user_id, int voice_length, String voice_path, boolean read, java.util.Date date_time) {
        this.id = id;
        this.owner = owner;
        this.type = type;
        this.target_id = target_id;
        this.user_id = user_id;
        this.voice_length = voice_length;
        this.voice_path = voice_path;
        this.read = read;
        this.date_time = date_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getOwner() {
        return owner;
    }

    public void setOwner(int owner) {
        this.owner = owner;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public int getTarget_id() {
        return target_id;
    }

    public void setTarget_id(int target_id) {
        this.target_id = target_id;
    }

    public int getUser_id() {
        return user_id;
    }

    public void setUser_id(int user_id) {
        this.user_id = user_id;
    }

    public int getVoice_length() {
        return voice_length;
    }

    public void setVoice_length(int voice_length) {
        this.voice_length = voice_length;
    }

    @NotNull
    public String getVoice_path() {
        return voice_path;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVoice_path(@NotNull String voice_path) {
        this.voice_path = voice_path;
    }

    public boolean getRead() {
        return read;
    }

    public void setRead(boolean read) {
        this.read = read;
    }

    @NotNull
    public java.util.Date getDate_time() {
        return date_time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate_time(@NotNull java.util.Date date_time) {
        this.date_time = date_time;
    }

}
